sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    Product Team->>ISSO: Request system categorization
    Note over Product Team,ISSO: Email
    ISSO-->>Owner: What purpose?
    ISSO-->>Product Team: With what data? What does it do? How does it work?
    Product Team-->>ISSO: Define information types
    ISSO-->>ISSO: Categorize system based on info types
    Product Team-->>Product Team: Draft security plan
    Note over Product Team: OSCAL SSP file in VCS
    Product Team-->>ISSO: Send draft categorization in plan for review
    Note over Product Team: Upload OSCAL SSP in GRC with API
    ISSO-->>Product Team: Categorization ok, proceed