sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    ISSO->>ISSO: Select controls
    Note over ISSO: Update SSP in GRC
    ISSO-->>Product Team: Announce controls
    Note over ISSO, Product Team: Email
