sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    Product Team->>+Product Team: Implement the system.
    Product Team-->>+ISSO: Submit security plan for review, request assessment
    ISSO-->>+ISSO: Determine assessment readiness