sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    actor Assessor
    ISSO->>+Assessor: Initiate assessment
    Assessor-->>+Assessor: Review controls and system
    Assessor-->>+Assessor: Draft assessment plan