sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    actor Assessor
    ISSO-->>ISSO: Update SSP with owner approval
    Note over ISSO: Update SSP in GRC with approval
    ISSO->>Owner: Authorize system
    Product Team->>Product Team: Deploy system
    Note over Product Team: Export OSCAL SSP and POA&M from GRC to VCS
    Product Team->>Owner: Announce system go-live status