sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    actor Assessor
    ISSO->>Assessor: Initiate assessment
    Note over ISSO: Update SSP in GRC
    Assessor-->>Assessor: Review controls and system
    Assessor-->>Assessor: Draft assessment plan
    Note over Assessor: Create AP in GRC
