sequenceDiagram
    actor Owner
    actor Product Team
    actor ISSO
    ISSO-->>ISSO: Categorize system based on info types
    Product Team-->>Product Team: Draft security plan
    Note over Product Team: OSCAL SSP file in VCS
