sequenceDiagram
    actor Owner
    actor Product Team
    %% Prepare
    Owner->>+Owner: Start a new project and its system
    Owner-->>+Owner: Describe the system
    Owner-->>+Product Team: Send project description and system requirements