graph LR;
    subgraph "AwesomeCloud IaaS"
        subgraph "AwesomeCloud Compute Server"
            subgraph "Web Application"
                api(API Service)
                admin(Admin Frontend)
                publicinfo(User Frontend)
            end
            db(Postgres Database)
        end
    end