@startuml ifa_goodread_system_unified_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Boundary(awesomecloud, "AwesomeCloud IaaS") {
    Boundary(awesomecloud-ifa, "IFA AwesomeCloud Environment") {
        Boundary(ifa-goodread, "AwesomeCloud Compute Server for IFA GoodRead") {
            Boundary(backend, "Django web application") {
                System(api, "REST API", "DRF")
                System(admin, "Django Admin interface")
                System(submissions, "Django authenticated frontend")
                System(publicinfo, "Django unauthenticated frontend")
            }
            System(db, "Database", "Postgres")
        }
    }
}

@enduml
